version: '3.8'

services:
  skillpoint-postgres:
    container_name: skillpoint-postgres
    image: postgres:latest
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging: 
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes: 
      - skillpoint-postgres-volume:/var/lib/postrgesql/data

volumes:
  skillpoint-postgres-volume: